# Generated by Django 2.0 on 2020-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='type',
            field=models.IntegerField(choices=[(1, '开发'), (2, '运维'), (3, '产品'), (4, '测试')]),
        ),
    ]
