# Generated by Django 2.0 on 2020-05-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200516_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='type',
            field=models.IntegerField(choices=[(0, '开发'), (1, '运维'), (2, '产品'), (3, '测试')]),
        ),
    ]
